### ISSUE TITLE
Bionics still lack description in medical tab

### ISSUE THREAD

**Issue by Zaks-ffa** [edbmods/EdBPrepareCarefully#298]
After months bionics tab still lacks descriptions which is very annoying if you have multiple mods adding 2 different bionics under the same name. i cant tell which is which so i imo just like with traits and backstory every bionic listed should show effects it has on hoover

**Comment by RoyalRedKing** [comment]
Actually you are correct and incorrect at the same time. yes they dont have a description(in the menu) but as soon as you put them on they still wont have one but once you have to put a throwaway and remove it and the description will show for all the others. You have to do this every single time you add or remove. Would be great if it was fixed tho since its very annoying to keep doing every single time.

**Comment by edbmods** [comment]
Very old request, but there are some fixes for this going in to a 1.3 version of the mod soon.
